# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'toDoListApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for toDoListApp
    pod 'Firebase/Core'
    pod 'Firebase/Database'
    pod 'Firebase/Storage'
    pod 'Firebase/Auth'


end
